language: csharp
solution: Sider.sln
mono: none
dotnet: 2.1.502
addons:
  chrome: stable
install:
  - dotnet restore
script:
  - dotnet build --configuration Release
  - dotnet test --configuration Release

